print("[BobBlocks By minetest@rabbibob.com] Version 0.0.8 loading....")
dofile(minetest.get_modpath("bobblocks") .. "/blocks.lua")
dofile(minetest.get_modpath("bobblocks") .. "/health.lua")
dofile(minetest.get_modpath("bobblocks") .. "/trap.lua")
print("[BobBlocks By minetest@rabbibob.com] Version 0.0.8 loaded!")
